# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
import askmath.models.access.registerkey
from django.conf import settings
import askMathPlus.components_metro


class Migration(migrations.Migration):

    dependencies = [
        ('askmath', '0003_auto_20151006_0419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'Administrator', 'verbose_name_plural': 'Administrators'},
        ),
        migrations.AlterModelOptions(
            name='administratorkey',
            options={'ordering': ['user'], 'verbose_name': 'Chave do Administrador', 'verbose_name_plural': 'Chaves dos Administradores'},
        ),
        migrations.AlterModelOptions(
            name='answeredquestionshistoric',
            options={'ordering': ['-discipline'], 'verbose_name': 'Hist\xf3rico da Quest\xe3o Resolvida', 'verbose_name_plural': 'Hist\xf3rico de Quest\xf5es Resolvidas'},
        ),
        migrations.AlterModelOptions(
            name='assistant',
            options={'verbose_name': 'Assistant', 'verbose_name_plural': 'Assistants'},
        ),
        migrations.AlterModelOptions(
            name='assistantkey',
            options={'ordering': ['user'], 'verbose_name': 'Chave do Assistente', 'verbose_name_plural': 'Chave do Assistente'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['title'], 'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='helpquestionshistoric',
            options={'ordering': ['-discipline'], 'verbose_name': 'Hist\xf3rico do Pedido de Ajuda', 'verbose_name_plural': 'Hist\xf3rico de Pedidos de Ajuda'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['position'], 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['creation'], 'verbose_name': 'Curtir', 'verbose_name_plural': 'Curtis'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['creation'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position'], 'verbose_name': 'Quest\xe3o', 'verbose_name_plural': 'Quest\xf5es'},
        ),
        migrations.AlterModelOptions(
            name='skippedquestionshistoric',
            options={'ordering': ['-discipline'], 'verbose_name': 'Hist\xf3rico o Salto Realizado', 'verbose_name_plural': 'Hist\xf3rico de Saltos Realizados'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='studentexperience',
            options={'ordering': ['-student'], 'verbose_name': 'Experi\xeancia do Estudante', 'verbose_name_plural': 'Experi\xeancias dos Estudantes'},
        ),
        migrations.AlterModelOptions(
            name='studenthistoric',
            options={'ordering': ['-student'], 'verbose_name': 'Hist\xf3rico de Estudante', 'verbose_name_plural': 'Hist\xf3rico de Estudantes'},
        ),
        migrations.AlterModelOptions(
            name='studentlessonstate',
            options={'ordering': ['-discipline'], 'verbose_name': 'Estado do Estudante nas Li\xe7\xf5es', 'verbose_name_plural': 'Estado das Li\xe7\xf5es dos Estudantes'},
        ),
        migrations.AlterModelOptions(
            name='studentquestionprogress',
            options={'ordering': ['-discipline'], 'verbose_name': 'Progresso da Quest\xe3o', 'verbose_name_plural': 'Progresso das Quest\xf5es'},
        ),
        migrations.AlterModelOptions(
            name='studentvideoprogress',
            options={'ordering': ['-discipline'], 'verbose_name': 'Progresso do V\xeddeo', 'verbose_name_plural': 'Progresso do V\xeddeo'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='teacherkey',
            options={'ordering': ['user'], 'verbose_name': 'Chave do Professor', 'verbose_name_plural': 'Chaves dos Professores'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-creation'], 'verbose_name': 'T\xf3pico', 'verbose_name_plural': 'T\xf3picos'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['position'], 'verbose_name': 'V\xeddeo', 'verbose_name_plural': 'V\xeddeos'},
        ),
        migrations.AlterField(
            model_name='administratorkey',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='administratorkey',
            name='creator',
            field=models.ForeignKey(verbose_name='Pessoa', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='administratorkey',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='administratorkey',
            name='in_use',
            field=models.BooleanField(default=False, verbose_name='Em Uso'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='administratorkey',
            name='key',
            field=models.CharField(default=askmath.models.access.registerkey.generate_key, max_length=100, verbose_name='Chave'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answeredquestionshistoric',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answeredquestionshistoric',
            name='discipline',
            field=models.ForeignKey(verbose_name='Disciplina', to='askmath.Discipline'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answeredquestionshistoric',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answeredquestionshistoric',
            name='hit',
            field=models.BooleanField(default=False, verbose_name='Acerto'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answeredquestionshistoric',
            name='items',
            field=models.ManyToManyField(to='askmath.Item', verbose_name='Itens'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answeredquestionshistoric',
            name='lesson',
            field=models.ForeignKey(verbose_name='Li\xe7\xe3o', to='askmath.Lesson'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answeredquestionshistoric',
            name='question',
            field=models.ForeignKey(verbose_name='Quest\xe3o', to='askmath.Question'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='assistantkey',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='assistantkey',
            name='creator',
            field=models.ForeignKey(verbose_name='Pessoa', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='assistantkey',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='assistantkey',
            name='in_use',
            field=models.BooleanField(default=False, verbose_name='Em Uso'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='assistantkey',
            name='key',
            field=models.CharField(default=askmath.models.access.registerkey.generate_key, max_length=100, verbose_name='Chave'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default=askMathPlus.components_metro.generate_color, help_text='Escolha uma cor para a categoria.', max_length=50, verbose_name='Cor', choices=[(b'bg-lime', b'Lime'), (b'bg-green', b'Green'), (b'bg-emerald', b'Emerald'), (b'bg-teal', b'Teal'), (b'bg-blue', b'Blue'), (b'bg-cyan', b'Cyan'), (b'bg-cobalt', b'Cobalt'), (b'bg-indigo', b'Indigo'), (b'bg-violet', b'Violet'), (b'bg-magenta', b'Magenta'), (b'bg-orange', b'Orange'), (b'bg-amber', b'Amber'), (b'bg-yellow', b'Yellow'), (b'bg-brown', b'Brown'), (b'bg-olive', b'Emerald'), (b'bg-steel', b'Steel'), (b'bg-mauve', b'Mauve'), (b'bg-taupe', b'Taupe'), (b'bg-gray', b'Gray'), (b'bg-lightBlue', b'Light Blue'), (b'bg-lightRed', b'Light Red'), (b'bg-lightGreen', b'Light Green'), (b'bg-lighterBlue', b'Lighter Blue'), (b'bg-lightOlive', b'Light Olive'), (b'bg-lightOrange', b'Light Orange')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='category',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(help_text='Escolha uma descri\xe7\xe3o para a categoria.', max_length=100, null=True, verbose_name='Descri\xe7\xe3o', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='category',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='category',
            name='person',
            field=models.ForeignKey(verbose_name='Pessoa', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Escolha um t\xedtulo para a categoria.', max_length=100, verbose_name='T\xedtulo'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discipline',
            name='color',
            field=models.CharField(default=askMathPlus.components_metro.generate_color, help_text='Escolha uma cor para a disciplina.', max_length=50, verbose_name='Cor', choices=[(b'bg-lime', b'Lime'), (b'bg-green', b'Green'), (b'bg-emerald', b'Emerald'), (b'bg-teal', b'Teal'), (b'bg-blue', b'Blue'), (b'bg-cyan', b'Cyan'), (b'bg-cobalt', b'Cobalt'), (b'bg-indigo', b'Indigo'), (b'bg-violet', b'Violet'), (b'bg-magenta', b'Magenta'), (b'bg-orange', b'Orange'), (b'bg-amber', b'Amber'), (b'bg-yellow', b'Yellow'), (b'bg-brown', b'Brown'), (b'bg-olive', b'Emerald'), (b'bg-steel', b'Steel'), (b'bg-mauve', b'Mauve'), (b'bg-taupe', b'Taupe'), (b'bg-gray', b'Gray'), (b'bg-lightBlue', b'Light Blue'), (b'bg-lightRed', b'Light Red'), (b'bg-lightGreen', b'Light Green'), (b'bg-lighterBlue', b'Lighter Blue'), (b'bg-lightOlive', b'Light Olive'), (b'bg-lightOrange', b'Light Orange')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discipline',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discipline',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discipline',
            name='responsible',
            field=models.CharField(default=1, help_text='Escolha uma respons\xe1vel para a disciplina.', max_length=100, verbose_name='Respons\xe1vel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discipline',
            name='title',
            field=models.CharField(help_text='Escolha uma t\xedtulo para a disciplina.', max_length=100, verbose_name='T\xedtulo'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discipline',
            name='visible',
            field=models.BooleanField(default=False, help_text='Selecione esta op\xe7\xe3o para tornas a disciplina vis\xedvel \xe0 todos.', verbose_name='Vis\xedvel'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='helpquestionshistoric',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='helpquestionshistoric',
            name='discipline',
            field=models.ForeignKey(verbose_name='Disciplina', to='askmath.Discipline'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='helpquestionshistoric',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='helpquestionshistoric',
            name='lesson',
            field=models.ForeignKey(verbose_name='Li\xe7\xe3o', to='askmath.Lesson'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='helpquestionshistoric',
            name='question',
            field=models.ForeignKey(verbose_name='Quest\xe3o', to='askmath.Question'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='item',
            name='correct',
            field=models.BooleanField(default=False, help_text='Este item est\xe1 correto.', verbose_name='\xc9 correta'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='item',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='item',
            name='deficiencys',
            field=models.ManyToManyField(help_text='Escolha as poss\xedveis defici\xeancias que o aluno possa ter caso o mesmo responda mancando este item.', to='askmath.Lesson', null=True, verbose_name='Defici\xeancias', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text='Escolha uma descri\xe7\xe3o para este item.', verbose_name='Descri\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='item',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='item',
            name='position',
            field=models.IntegerField(help_text='Escolha uma posi\xe7\xe3o para este item.', null=True, verbose_name='Posi\xe7\xe3o', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='color',
            field=models.CharField(default=askMathPlus.components_metro.generate_color, help_text='Escolha uma cor para esta li\xe7\xe3o.', max_length=50, verbose_name='Cor', choices=[(b'bg-lime', b'Lime'), (b'bg-green', b'Green'), (b'bg-emerald', b'Emerald'), (b'bg-teal', b'Teal'), (b'bg-blue', b'Blue'), (b'bg-cyan', b'Cyan'), (b'bg-cobalt', b'Cobalt'), (b'bg-indigo', b'Indigo'), (b'bg-violet', b'Violet'), (b'bg-magenta', b'Magenta'), (b'bg-orange', b'Orange'), (b'bg-amber', b'Amber'), (b'bg-yellow', b'Yellow'), (b'bg-brown', b'Brown'), (b'bg-olive', b'Emerald'), (b'bg-steel', b'Steel'), (b'bg-mauve', b'Mauve'), (b'bg-taupe', b'Taupe'), (b'bg-gray', b'Gray'), (b'bg-lightBlue', b'Light Blue'), (b'bg-lightRed', b'Light Red'), (b'bg-lightGreen', b'Light Green'), (b'bg-lighterBlue', b'Lighter Blue'), (b'bg-lightOlive', b'Light Olive'), (b'bg-lightOrange', b'Light Orange')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(help_text='Escolha uma descri\xe7\xe3o para a li\xe7\xe3o.', verbose_name='Descri\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='discipline',
            field=models.ForeignKey(verbose_name='Disciplina', to='askmath.Discipline', help_text='Escolha uma disciplina para a li\xe7\xe3o.'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='maximum_hops',
            field=models.IntegerField(help_text='Escolha o n\xfamero m\xe1ximo de saltos que o aluno pode realizar nessa li\xe7\xe3o.', verbose_name='M\xe1ximo de Saltos'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='requirements',
            field=models.ManyToManyField(related_name='Requirements', to='askmath.Lesson', blank=True, help_text='Escolha as li\xe7\xe3o que s\xe3o recomendadas seguir antes de iniciar esta.', null=True, verbose_name='Requisitos'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='sugestions',
            field=models.ManyToManyField(related_name='Sugestions', to='askmath.Lesson', blank=True, help_text='Escolha as li\xe7\xe3o que s\xe3o recomendadas seguir ap\xf3s a conclus\xe3o desta.', null=True, verbose_name='Sugest\xf5es'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='Escolha uma t\xedtulo para a li\xe7\xe3o.', max_length=50, verbose_name='T\xedtulo'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='visible',
            field=models.BooleanField(default=False, help_text='Escolha esta op\xe7\xe3o para tornar a li\xe7\xe3o vis\xedvel \xe0 todos.'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='like',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='like',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='like',
            name='person',
            field=models.ForeignKey(verbose_name='Pessoa', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='message',
            name='color',
            field=models.CharField(default=askMathPlus.components_metro.generate_color, max_length=50, verbose_name='Cor'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='message',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(help_text='Entre com seu email.', max_length=254, verbose_name='Email'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='message',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(help_text='Realize upload de um arquivo.', upload_to=b'documents/contact_files/%Y/%m/%d', null=True, verbose_name='Arquivo', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(help_text='Voc\xea pode usar as tags HTML: <a href=\'\' title=\'\'> <abbr title = ""> <acronym title = ""> <b> <blockquote citar = ""> <cite> <code> <del datetime = \'\'> <em> <i> <q cite = ""> <strike> <strong>', max_length=2000, verbose_name='Mensagem'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(help_text='Entre com seu nome.', max_length=100, verbose_name='Nome'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='color',
            field=models.CharField(default=askMathPlus.components_metro.generate_color, help_text='Escolha uma cor para esta quest\xe3o.', max_length=50, verbose_name='Cor', choices=[(b'bg-lime', b'Lime'), (b'bg-green', b'Green'), (b'bg-emerald', b'Emerald'), (b'bg-teal', b'Teal'), (b'bg-blue', b'Blue'), (b'bg-cyan', b'Cyan'), (b'bg-cobalt', b'Cobalt'), (b'bg-indigo', b'Indigo'), (b'bg-violet', b'Violet'), (b'bg-magenta', b'Magenta'), (b'bg-orange', b'Orange'), (b'bg-amber', b'Amber'), (b'bg-yellow', b'Yellow'), (b'bg-brown', b'Brown'), (b'bg-olive', b'Emerald'), (b'bg-steel', b'Steel'), (b'bg-mauve', b'Mauve'), (b'bg-taupe', b'Taupe'), (b'bg-gray', b'Gray'), (b'bg-lightBlue', b'Light Blue'), (b'bg-lightRed', b'Light Red'), (b'bg-lightGreen', b'Light Green'), (b'bg-lighterBlue', b'Lighter Blue'), (b'bg-lightOlive', b'Light Olive'), (b'bg-lightOrange', b'Light Orange')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(help_text='Escolha uma descri\xe7\xe3o para esta pergunta.', verbose_name='Descri\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='help',
            field=models.TextField(help_text='Escolha uma ajuda para esta pergunta.', null=True, verbose_name='Ajuda', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='items',
            field=models.ManyToManyField(help_text='Escolha os itens que esta pergunta tem.', to='askmath.Item', verbose_name='Itens'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(verbose_name='Li\xe7\xe3o', to='askmath.Lesson', help_text='Escolha uma li\xe7\xe3o para esta pergunta.'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.IntegerField(help_text='Escolha uma posi\xe7\xe3o para esta pergunta.', verbose_name='Posi\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='scores',
            field=models.IntegerField(verbose_name='Pontos', choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8'), (9, b'9'), (10, b'10')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='visible',
            field=models.BooleanField(default=False, help_text='Selecione esta op\xe7\xe3o para tornar esta quest\xe3o vis\xedvel \xe0 todos.', verbose_name='Vis\xedvel'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='skippedquestionshistoric',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='skippedquestionshistoric',
            name='discipline',
            field=models.ForeignKey(verbose_name='Disciplina', to='askmath.Discipline'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='skippedquestionshistoric',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='skippedquestionshistoric',
            name='lesson',
            field=models.ForeignKey(verbose_name='Li\xe7\xe3o', to='askmath.Lesson'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='skippedquestionshistoric',
            name='question',
            field=models.ForeignKey(verbose_name='Quest\xe3o', to='askmath.Question'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentexperience',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentexperience',
            name='level',
            field=models.IntegerField(default=1, verbose_name='N\xedvel'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentexperience',
            name='max_scores',
            field=models.IntegerField(default=10, verbose_name='M\xe1ximo de Pontos'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentexperience',
            name='scores',
            field=models.IntegerField(default=0, verbose_name='Pontos'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentexperience',
            name='stars',
            field=models.IntegerField(default=0, verbose_name='Estrelas'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentexperience',
            name='student',
            field=models.ForeignKey(verbose_name='Estudante', to='askmath.Student'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studenthistoric',
            name='answered_questions_historic',
            field=models.ManyToManyField(related_name='Hist\xf3rico de Quest\xf5es Resolvidas', null=True, verbose_name='Hist\xf3rico de Quest\xf5es Resolvidas', to='askmath.AnsweredQuestionsHistoric', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studenthistoric',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studenthistoric',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studenthistoric',
            name='help_questions_historic',
            field=models.ManyToManyField(related_name='Help Question Historic', null=True, verbose_name='Hist\xf3rico de Quest\xf5es Resolvidas', to='askmath.HelpQuestionsHistoric', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studenthistoric',
            name='skipped_questions_historic',
            field=models.ManyToManyField(related_name='Skipped Question Historic', null=True, verbose_name='Hist\xf3rico de Quest\xf5es Resolvidas', to='askmath.SkippedQuestionsHistoric', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studenthistoric',
            name='student',
            field=models.ForeignKey(verbose_name='Estudante', to='askmath.Student'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentlessonstate',
            name='answered_correct_questions',
            field=models.ManyToManyField(related_name='Answered Correct Questions', null=True, verbose_name='Quest\xf5es Respondidas', to='askmath.Question', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentlessonstate',
            name='answered_incorrect_questions',
            field=models.ManyToManyField(related_name='Answered Incorrect Questions', null=True, verbose_name='Quest\xf5es Respondidas', to='askmath.Question', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentlessonstate',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentlessonstate',
            name='discipline',
            field=models.ForeignKey(verbose_name='Disciplina', to='askmath.Discipline'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentlessonstate',
            name='errors_followed',
            field=models.IntegerField(default=0, verbose_name='Erros Seguidos'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentlessonstate',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentlessonstate',
            name='help_questions',
            field=models.ManyToManyField(related_name='Help Questions', null=True, verbose_name='Quest\xf5es de Ajuda', to='askmath.Question', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentlessonstate',
            name='hits_followed',
            field=models.IntegerField(default=0, verbose_name='Acertos Seguidos'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentlessonstate',
            name='lesson',
            field=models.ForeignKey(verbose_name='Li\xe7\xe3o', to='askmath.Lesson'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentlessonstate',
            name='percentage_completed',
            field=models.IntegerField(default=0, verbose_name='Porcentagem Completo'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentlessonstate',
            name='remaining_jump',
            field=models.IntegerField(default=0, verbose_name='Saltos Restantes'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentlessonstate',
            name='scores',
            field=models.IntegerField(default=0, verbose_name='Pontos'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentlessonstate',
            name='skipped_questions',
            field=models.ManyToManyField(related_name='Skipped Questions', null=True, verbose_name='Quest\xf5es Saltadas', to='askmath.Question', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentlessonstate',
            name='student',
            field=models.ForeignKey(verbose_name='Estudante', to='askmath.Student'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentquestionprogress',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentquestionprogress',
            name='discipline',
            field=models.ForeignKey(verbose_name='Disciplina', to='askmath.Discipline'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentquestionprogress',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentquestionprogress',
            name='lesson',
            field=models.ForeignKey(verbose_name='Li\xe7\xe3o', to='askmath.Lesson'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentquestionprogress',
            name='question',
            field=models.ForeignKey(verbose_name='Quest\xe3o', to='askmath.Question'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentquestionprogress',
            name='student',
            field=models.ForeignKey(verbose_name='Estudante', to='askmath.Student'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentvideoprogress',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentvideoprogress',
            name='discipline',
            field=models.ForeignKey(verbose_name='Disciplina', to='askmath.Discipline'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentvideoprogress',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentvideoprogress',
            name='lesson',
            field=models.ForeignKey(verbose_name='Li\xe7\xe3o', to='askmath.Lesson'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentvideoprogress',
            name='student',
            field=models.ForeignKey(verbose_name='Estudante', to='askmath.Student'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='studentvideoprogress',
            name='video',
            field=models.ForeignKey(verbose_name='V\xeddeo', to='askmath.Video'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='teacherkey',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='teacherkey',
            name='creator',
            field=models.ForeignKey(verbose_name='Pessoa', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='teacherkey',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='teacherkey',
            name='in_use',
            field=models.BooleanField(default=False, verbose_name='Em Uso'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='teacherkey',
            name='key',
            field=models.CharField(default=askmath.models.access.registerkey.generate_key, max_length=100, verbose_name='Chave'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(verbose_name='Categoria', to='askmath.Category'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='topic',
            name='color',
            field=models.CharField(default=askMathPlus.components_metro.generate_color, help_text='Escolha uma cor para este t\xf3pico.', max_length=50, verbose_name='Cor', choices=[(b'bg-lime', b'Lime'), (b'bg-green', b'Green'), (b'bg-emerald', b'Emerald'), (b'bg-teal', b'Teal'), (b'bg-blue', b'Blue'), (b'bg-cyan', b'Cyan'), (b'bg-cobalt', b'Cobalt'), (b'bg-indigo', b'Indigo'), (b'bg-violet', b'Violet'), (b'bg-magenta', b'Magenta'), (b'bg-orange', b'Orange'), (b'bg-amber', b'Amber'), (b'bg-yellow', b'Yellow'), (b'bg-brown', b'Brown'), (b'bg-olive', b'Emerald'), (b'bg-steel', b'Steel'), (b'bg-mauve', b'Mauve'), (b'bg-taupe', b'Taupe'), (b'bg-gray', b'Gray'), (b'bg-lightBlue', b'Light Blue'), (b'bg-lightRed', b'Light Red'), (b'bg-lightGreen', b'Light Green'), (b'bg-lighterBlue', b'Lighter Blue'), (b'bg-lightOlive', b'Light Olive'), (b'bg-lightOrange', b'Light Orange')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='topic',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(help_text='Escolha uma descri\xe7\xe3o para esse t\xf3pico.', verbose_name='Descri\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='topic',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='topic',
            name='file',
            field=models.FileField(help_text='Realize upload de um arquivo.', upload_to=b'documents/forum/topic/%Y/%m/%d', null=True, verbose_name='Arquivo', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='topic',
            name='likes',
            field=models.ManyToManyField(to='askmath.Like', null=True, verbose_name='Curtis', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='topic',
            name='person',
            field=models.ForeignKey(verbose_name='Pessoa', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=255, verbose_name='T\xedtulo'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='video',
            name='color',
            field=models.CharField(default=askMathPlus.components_metro.generate_color, help_text='Escolha uma cor para o v\xeddeo.', max_length=50, verbose_name='Cor', choices=[(b'bg-lime', b'Lime'), (b'bg-green', b'Green'), (b'bg-emerald', b'Emerald'), (b'bg-teal', b'Teal'), (b'bg-blue', b'Blue'), (b'bg-cyan', b'Cyan'), (b'bg-cobalt', b'Cobalt'), (b'bg-indigo', b'Indigo'), (b'bg-violet', b'Violet'), (b'bg-magenta', b'Magenta'), (b'bg-orange', b'Orange'), (b'bg-amber', b'Amber'), (b'bg-yellow', b'Yellow'), (b'bg-brown', b'Brown'), (b'bg-olive', b'Emerald'), (b'bg-steel', b'Steel'), (b'bg-mauve', b'Mauve'), (b'bg-taupe', b'Taupe'), (b'bg-gray', b'Gray'), (b'bg-lightBlue', b'Light Blue'), (b'bg-lightRed', b'Light Red'), (b'bg-lightGreen', b'Light Green'), (b'bg-lighterBlue', b'Lighter Blue'), (b'bg-lightOlive', b'Light Olive'), (b'bg-lightOrange', b'Light Orange')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='video',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Cria\xe7\xe3o'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(help_text='Escolha uma descri\xe7\xe3o para o v\xeddeo.', null=True, verbose_name='Descri\xe7\xe3o', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='video',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Existe'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(help_text='Realize upload de um arquivo.', upload_to=b'documents/video/%Y/%m/%d', verbose_name='Arquivo'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(verbose_name='Li\xe7\xe3o', to='askmath.Lesson', help_text='Escolha uma li\xe7\xe3o para o v\xeddeo.'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='video',
            name='position',
            field=models.IntegerField(help_text='Escolha uma posi\xe7\xe3o para o v\xeddeo.', null=True, verbose_name='Posi\xe7\xe3o', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(help_text='Escolha um t\xedtulo para o v\xeddeo.', max_length=50, verbose_name='T\xedtulo'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='video',
            name='visible',
            field=models.BooleanField(default=False, help_text='Selecione esta op\xe7\xe3o para tornar esse v\xeddeo vis\xedvel \xe0 todos.', verbose_name='Vis\xedvel'),
            preserve_default=True,
        ),
    ]
